print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you'not'.")
print('I "said do not touch this.')
# printing the strings
print("OMG")
print("eat everything")
print("Ok Harry ")
print("Yepp.It's over")
print("keep the mouse in place")
print("That's you in Paris")
print("That you own a villa ")
print("Rama")